#!/bin/bash
# - klg: show pod logs
#   - example: `klg pod`
#   - example: `klg pod -f`
#   - example: `klg pod:container`

if [ -z "$1" ]; then
  kubectl get pod
  exit
fi

target=${1%:*}
container=${1##*:}
if [ "$target" == "$1" ]; then container=""; fi
shift

pod=`kubectl get pod | grep $target | head -n1 | awk '{print $1}'`

if [ -z "$pod" ]; then
  echo no pod found.
  exit
fi

if [ -n "$container" ]; then
  kubectl logs $pod -c $container $@
else
  kubectl logs $pod $@
fi
