#!/bin/bash
# - kls: list or describe a pod
#   - example: `kls`
#   - example: `kls pod`

if [ -z "$1" ]; then
  kubectl get pod
  exit
fi

pod=`kubectl get pod | grep $1 | head -n1 | awk '{print $1}'`

if [ -z "$pod" ]; then
  echo no pod found.
  exit
fi

kubectl describe pod $pod
