#!/bin/bash
# - kns: set namespace and context from working directory (or from arg)
#   - assumes path format of ./context/namespace
#   - example: `kns`
#   - example: `kns staging`

p=`pwd`
path=`dirname $p`
target=`basename $path`
ctx=`kubectl config get-contexts | grep $target | awk '{print $1}'`

if [[ -n "$ctx" && "$ctx" != "*" ]]; then
  kubectl config use-context $ctx
fi

folder=`basename $p`
ns=${1:-$folder}
kubectl config set-context `kubectl config current-context` --namespace $ns

echo namespace: $ns

if [ "$folder" != "$ns" ]; then
  echo "*********************************"
  echo "** MISMATCHED folder/namespace **"
  echo "*********************************"
fi
