#!/bin/bash
# - kup: upload file to pod
#   - example: `kup filename pod`
#   - example: `kup filename pod:/path`
#   - example: `kup filename pod:container:`
#   - example: `kup filename pod:container:/path`
#   - invalid: `kup filename pod:container`

if [ -z "$2" ]; then
  kubectl get pod
  exit
fi

src=$1
if [ ! -f "$src" ]; then
  echo missing file $fn
  exit
fi

resource=${2%:*}
path=${2##*:}
if [ "$resource" == "$2" ]; then path=""; fi

target=${resource%:*}
container=${resource##*:}
if [ "$target" == "$resource" ]; then container=""; fi

pod=`kubectl get pod | grep $target | head -n1 | awk '{print $1}'`

if [ -z "$pod" ]; then
  echo no pod found.
  exit
fi

fn=${path##*/}
dst=${path%/*}
if [ -z "$fn" ]; then fn=`basename $src`; fi

if [ -n "$container" ]; then
  kubectl cp $src $pod:$dst/$fn -c $container
else
  kubectl cp $src $pod:$dst/$fn
fi
